services:
  gpustack-master:
    image: gpustack/gpustack:${VERSION:-latest}
    container_name: gpustack-master
    network_mode: host
    ipc: host
    volumes:
      - "${VOLUME_BASE_DIR:-./volume}:/var/lib/gpustack"
