services:
  gpustack-master:
    image: gpustack/gpustack:${VERSION:-latest}
    container_name: gpustack-master
    network_mode: host
    ipc: host
    command: [
      "--port", "${GPUSTACK_PORT:-8080}"
    ]
    volumes:
      - "${VOLUME_BASE_DIR:-./volume}:/var/lib/gpustack"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia
